Repository tokiwa-software/fzweb, pull requests merged in 2025-09, with the labels that each got.

#101 src: move features related to parsing tags from Session to document
  src/Session.fz
  src/content.fz
  src/document.fz
Labels: cleanup

#117 show/log errors on some failures
  src/Session.fz
  src/user.fz
Labels: enhancement

#128 src/webserver/connection_handler: add comments to some features
  src/webserver/connection_handler.fz
Labels: documentation
